version: "3.8"

services:
  web:
    image: php:8.1-apache
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"  # Instalar MySQLi y luego iniciar Apache
    volumes:
      - /e/docker-proyectos/practica-app-php/app:/var/www/html  #Ruta de Windows convertida a formato de Docker
    ports:
      - "8080:80"
    secrets:
      - db_password
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: claveSuperSegura123
      MYSQL_DATABASE: miapp
    volumes:
      - /e/docker-volumes/db_data:/var/lib/mysql      
    secrets:
      - db_password
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  db_password:
    external: true