name: Deploy BDD PHP MySql

on:
  push:
    branches:
      - main  # Desplegar cuando haya un push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest  # El trabajo se ejecutará en un contenedor Ubuntu
    
    steps:
    # Paso 1: Comprobar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Paso 2: Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    # Paso 3: Verificar las variables de entorno
    - name: Verificar las variables de entorno
      run: |
        echo "IP del servidor: ${{ secrets.SERVER_IP }}"
        echo "Usuario: ${{ secrets.SERVER_USER }}"
        echo "Puerto SSH: ${{ secrets.SERVER_SSH_PORT }}"
    
    # Paso 4: Construir la imagen Docker
    - name: Build Docker image
      run: docker-compose -f docker-compose.yml build
    
    # Paso 5: Subir la imagen a Docker Hub (si lo necesitas)
    - name: Push Docker image to Docker Hub
      run: docker-compose -f docker-compose.yml push
    
    # Paso 6: Desplegar en un servidor remoto (usa SSH para conectar al servidor y hacer deploy)
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
         host: ${{ secrets.SERVER_IP }}
         username: ${{ secrets.SERVER_USER }}
         password: ${{ secrets.SERVER_PASSWORD }}
         port: ${{ secrets.SERVER_PORT }}  # Cambiar vars a secrets  
         script: |
          cd /e/docker-proyectos/practica-app-php
          docker-compose down
          docker-compose pull
          docker-compose up -d